# Generated by Django 2.1.15 on 2020-06-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
